name: test

on:
  push:
    branches: [main]
  pull_request:

env:
  POETRY_VERSION: "1.3.1"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SERPAPI_API_KEY: "dummy"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==$POETRY_VERSION
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        # need to manually install langchain-experimental due to version conflicts
        run: |
          poetry install
          poetry run pip install langchain-experimental==0.0.47
      - name: Run unit tests
        run: |
          make tests
